### ISSUE TITLE
Use without require?

### ISSUE THREAD

**Issue by ianbale** [nickyout/fast-stable-stringify#2]
Hi,

I'd like to give this a whirl in an Ember project I am working on, but I am having problems with it.

I don't think I can use:
   _var stringify = require('fast-stable-stringify');_ 

since that just throws an error. I've added the package to my package.json so that it gets included in the project but I don't seem to be able to execute the stringify function. I've tried using simpleStableStringify({}) but that also fails.

I'm sure I'm missing something simple...but this is setup differently to anything I have used so far. Can you offer any suggestion?

Thanks,

ian

**Comment by nickyout** [comment]
Very strange. That is exactly how you should use it. I just tried installing it here and that line works. Can you post what exactly you ran and what error you received? 

For the record, this is what I ran:

```
var stringify = require('fast-stable-stringify');
stringify({ some: 'value' });
```

And no, I don't expose globals. I think that's very bad practice. 

What you could also try is to simply remove the fast-stable-stringify directory inside node_modules and just install it again. Perhaps there was a hiccup in the installation process and you simply did not get the whole module. It wouldn't be the first time I resolve an issue with npm by simply removing the node_modules dir and reinstalling everything.

**Comment by nickyout** [comment]
I guess this is no longer relevant.

**Comment by ianbale** [comment]
Hi. 

Sorry I didn't even notice your response. I'm not working on that project anymore - moved onto work for other clients. I can't recall what I ended up doing instead.

However, I'm using that library just fine in a nodejs application. No issues at all.
