### ISSUE TITLE
Does not return a valid JSON string in certain cases

### ISSUE THREAD

**Issue by NawarA** [nickyout/fast-stable-stringify#6]
I've noticed commas `,` are sometimes left off when an object contains properties objects, and/or those properties, have objectives as properties. Aka objects that have objects as their values

Is it intentional to leave off the `,` from some key values? Or is this indeed a bug / edge case to patch?

**Comment by nickyout** [comment]
I can recall testing pretty much every configuration across, well, just about every desktop and mobile browser. It is supposed to do the same as json-stable-stringify... but faster. That should be all. 

But perhaps there is indeed a case I did not cover yet. Please give me a case where you get invalid json. I'm curious.

**Comment by NawarA** [comment]
yup...sorry for the delay! here's an example of invalid JSON as an output based on input
```javascript
const Stringify = require('json-stable-stringify');
const fastString = require('fast-stable-stringify');

const obj = {
        a: {
            e: {
                alpha: 'feed5c9cdae3cae69202a5af67fc99c5dc9e8d30e1aef8d294f6bfb0c2aad45a',
                beta: '4def11058e66f2d8824b1c1b54e5f6efe0537338c32be558ce4e1f8ce6b66893',
                theta: '9bcb68bad9e70e17ddebca3a6c668af59b13fd2e06f558ea00c259113bafda8c',
                phi: 'd50a4ace00559b04fe99f117cf942097f4293652ca4454492e67e2e36dccedea',
                omega: '111ce70909455ee61f8c53ff18701c557714972856708277a2d1ac9d7a7d7a13',
                delta: '66cee05cd51948b4ab02c1393fae28c2d557f92f21275ce1ca2ac69fff54b830'
            },
             f: {
                cat: true,
                dog: false,
                lizard: true,
                bird: false,
                fish: false,
                bug: false
            },
             secretAgent: 'For queen and country',
             james: 'His name',
             bond: 'His last name'
         },
        b: {
            g: { age: -6 }, f: {}
        },
        c: {
            h: {
                door: 'knob',
                window: 'sill',
                hallway: undefined
            },
             f: {},
             hdoor: 'knob',
             hwindow: 'sill',
             hhallway: undefined },
        d:{
             i: 0.69,
             j: 'english',
             k: '32bit',
             l: 8,
             m: '81448148184148141908',
             n: '2.1875',
             o: '10,true,true',
             p: 'hello world',
             q: 4,
             r: 1,
             s: 3,
             t: 'operating systems',
             u: 'versions'
         }
  };
console.log( Stringify(obj) === fastString(obj) );
// the library produces invalid JSON string.
// meanwhile json-stable-stringify produces a valid JSON string
```

**Comment by NawarA** [comment]
This is on Node 6.10.0 LTS

**Comment by nickyout** [comment]
I think I see why. Thanks a lot for the heads up. I need to fix this.

**Comment by NawarA** [comment]
No Problem! I thought I'd share, since I love your approach of the highest performance deterministic JSON stringify. I was thinking about writing this lib up myself, so I appreciate that you beat me to it. Great job on this lib! :)

**Comment by NawarA** [comment]
Any chance of releasing the fix you noticed? We'd love to fully switch over to this library, given it correctly makes JSON strings

**Comment by nickyout** [comment]
It was already 2 weeks ago, huh. Time flies.

I just made a fix and a simple test addition to cover this particular case. 

...and while checking the code, I found a simplification that appears to slightly improve speed :)

I will update the README and push a release right away.

**Comment by nickyout** [comment]
And it's done: 0.2.0. Tell me if it works for you.
