### ISSUE TITLE
Question: License switch

### ISSUE THREAD

**Issue by BernhardRode** [nickyout/fast-stable-stringify#7]
Hi, you are currently under a GPL-3 license, which is perfectly fine for me, personally. 

But for a developer in a corporate environment, that license is a problem for me.

Would it be possible to change the license over to something without a hard copyleft, like MIT...

**Comment by nickyout** [comment]
Oh, I did not realize. I read it, and I don't mind it switching to MIT. I'll do that when I have the time.

**Comment by nickyout** [comment]
I guess I'll bump the version number later. For now you should be able to put this in your package.json: 

```
"dependencies": {
    ...
    "fast-stable-stringify": "git+https://github.com/nickyout/fast-stable-stringify#d6415e11c8a2b0c7a113aceae5454c58d6d0c9e2"
}
```

**Comment by BernhardRode** [comment]
That's awesome! Thank you very much!
