### ISSUE TITLE
stringify Date object to iso string?

### ISSUE THREAD

**Issue by ericfong** [nickyout/fast-stable-stringify#8]
Trying to
```js
const stringify = require('fast-stable-stringify')
stringify(new Date()) 
// got "{}"
// expect "2017-09-13T16:24:13.631Z"
```

Just found that 
```
Unlike substack's, it does:
not check for .toJSON() methods on objects
```
Any way to enable this?

**Comment by nickyout** [comment]
I see the toJSON call is part of the spec. I admit I did not check this back when I created the lib. I just never had to use it. But I acknowledge that it would be better when the lib would adhere to the spec. 

I am working on a rewrite right now, and I will include the toJSON case among the tests. My intention was to be done with the rewrite before next monday. 

I will post here if there is any progress.

**Comment by nickyout** [comment]
Should work as desired now. 

Want to confirm?

**Comment by ericfong** [comment]
Thx. It works
